name: flutter_base
description: A Flutter base application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  audioplayers: ^0.17.3
  font_awesome_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
  fonts:
    - family: Sawarabi
      fonts:
        - asset: fonts/SawarabiMincho-Regular.ttf
